implement the oauth2 pkce extension
owncloud/oauth2 pull request #276
Opened 2020-11-26 14:59 UTC by C0rby

Implemented the PKCE extension according to the [RFC 7636](https://tools.ietf.org/pdf/rfc7636.pdf)

I tested it with the latest desktop client and the Android App and both worked.
It should also still work for client which do not send the PKCE parameters.

2020-11-26 14:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/oauth2?pullRequest=276) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/oauth2?pullRequest=276) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/oauth2?pullRequest=276) it.</sub>

2020-11-26 15:06 UTC, DeepDiver1975 requested changes
Nice!

2020-11-26 15:06 UTC, DeepDiver1975 commented on appinfo/database.xml
> +            <field>
not needed - you have this in the migration

2020-11-26 15:27 UTC, C0rby commented
I probably didn't need to update the version in `appinfo/info.xmll`, right? I just tried all kinds of things to get my changes running. :see_no_evil: But in the end all I needed was `occ migration:execute ...` :sweat_smile:

2020-11-27 12:38 UTC, DeepDiver1975 commented
This should be tested with phoenix as well.

2020-11-30 10:39 UTC, C0rby commented
Tested with phoenix. It works. :+1:

2020-11-30 11:25 UTC, DeepDiver1975 approved these changes

2020-11-30 16:11 UTC, merged